/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "RooBumpExp.h"

#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <Riostream.h>
#include <TMath.h>

#include <cmath>

ClassImp(RooBumpExp);

RooBumpExp::RooBumpExp(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _tau,
                        RooAbsReal& _A,
                        RooAbsReal& _B,
                        RooAbsReal& _C,
                        RooAbsReal& _cste)
   : RooAbsPdf(name,title),
   x("x","x",this,_x),
   tau("tau","tau",this,_tau),
   A("A","A",this,_A),
   B("B","B",this,_B),
   C("C","C",this,_C),
   cste("cste","cste",this,_cste)
{
}

RooBumpExp::RooBumpExp(RooBumpExp const &other, const char *name)
   : RooAbsPdf(other,name),
   x("x",this,other.x),
   tau("tau",this,other.tau),
   A("A",this,other.A),
   B("B",this,other.B),
   C("C",this,other.C),
   cste("cste",this,other.cste)
{
}


double RooBumpExp::evaluate() const 
{
   return RooBumpExp_evaluate(x, tau, A, B, C, cste); 
}

void RooBumpExp::doEval(RooFit::EvalContext &ctx) const 
{ 
   std::span<const double> xSpan = ctx.at(x);
   std::span<const double> tauSpan = ctx.at(tau);
   std::span<const double> ASpan = ctx.at(A);
   std::span<const double> BSpan = ctx.at(B);
   std::span<const double> CSpan = ctx.at(C);
   std::span<const double> csteSpan = ctx.at(cste);

   std::size_t n = ctx.output().size();
   for (std::size_t i = 0; i < n; ++i) {
      ctx.output()[i] = RooBumpExp_evaluate(xSpan.size() > 1 ? xSpan[i] : xSpan[0],
                               tauSpan.size() > 1 ? tauSpan[i] : tauSpan[0],
                               ASpan.size() > 1 ? ASpan[i] : ASpan[0],
                               BSpan.size() > 1 ? BSpan[i] : BSpan[0],
                               CSpan.size() > 1 ? CSpan[i] : CSpan[0],
                               csteSpan.size() > 1 ? csteSpan[i] : csteSpan[0]);
   }
} 
void RooBumpExp::translate(RooFit::Detail::CodeSquashContext &ctx) const
{
   ctx.addResult(this, ctx.buildCall("RooBumpExp_evaluate", x, tau, A, B, C, cste));
}
