/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooBumpExp_h
#define RooBumpExp_h

#include <TMath.h>
#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>

class RooBumpExp : public RooAbsPdf {
public:
   RooBumpExp() {}
   RooBumpExp(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _tau,
        RooAbsReal& _A,
        RooAbsReal& _B,
        RooAbsReal& _C,
        RooAbsReal& _cste);
  RooBumpExp(RooBumpExp const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooBumpExp(*this, newname); }
protected:

  RooRealProxy x ;
  RooRealProxy tau ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy cste ;

  double evaluate() const override;
  void doEval(RooFit::EvalContext &) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooBumpExp, 1) // Your description goes here...
};
inline double RooBumpExp_evaluate(double x, double tau, double A, double B, double C, double cste) 
{
  Double_t sigma = B + C * ((x - A) / A);
  return (TMath::Exp(x*tau)) / (TMath::Exp(-(x - A) * (x - A)/(2. * sigma * sigma)) + cste); 
}


#endif // RooBumpExp_h