/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooVWG_C_h
#define RooVWG_C_h

#include "RooMath.h"
#include "TMath.h"
#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>

class RooVWG_C : public RooAbsPdf {
public:
   RooVWG_C() {}
   RooVWG_C(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _A,
        RooAbsReal& _B,
        RooAbsReal& _C,
        RooAbsReal& _cste);
  RooVWG_C(RooVWG_C const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooVWG_C(*this, newname); }
protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy cste;

  double evaluate() const override;
  //void computeBatch(double* output, std::size_t size, RooFit::Detail::DataMap const&) const override;
  void doEval(RooFit::EvalContext &) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooVWG_C, 1) // Your description goes here...
};
inline double RooVWG_C_evaluate(double x, double A, double B, double C, double cste) 
{
  Double_t sigma = B + C * ((x - A) / A);
  return TMath::Exp(-(x - A) * (x - A)/(2. * sigma * sigma)) + cste;
}


#endif // RooVWG_h